# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : checkout repo
        uses: actions/checkout@v3

      - name : python installation
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name : run hello python
        run: python src/main.py
        
      - name : test
        run : |
          pip install coverage
        
      - name : coverage install
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov.info

      #- name : install coverage
      
      #- name : install pytest
